# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Webserver
version:      3.04
version_from: lib/Pod/Webserver.pm
installdirs:  site
requires:
    Carp:                          0
    File::Spec::Unix:              0
    IO::Socket:                    0
    Pod::Simple:                   3.01
    Pod::Simple::HTML:             0
    Pod::Simple::HTMLBatch:        0
    Pod::Simple::Progress:         0
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
